version: "3.9"

services:
  web:
    build: .
    command: python /bookstore/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-#fazqr%s91&8h)v_!kkb&3ho&d90(zbs^6_-vq*44da6@+$$1fj"
      - "DJANGO_DEBUG=True"
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: